apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opencode
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: private
  tls:
    - hosts:
        - opencode.kube.kalski.xyz
      secretName: opencode-tls
  rules:
    - host: opencode.kube.kalski.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opencode
                port:
                  number: 4096
