apiVersion: v1
kind: Service
metadata:
  name: opencode
  labels:
    app: opencode
spec:
  type: ClusterIP
  ports:
    - port: 4096
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: opencode
