apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  labels:
    release: observability
spec:
  endpoints:
    - port: http-minio
      path: /minio/v2/metrics/cluster
  selector:
    matchLabels:
      app: minio
