apiVersion: v1
kind: Service
metadata:
  name: mktxp-exporter
  namespace: monitoring
  labels:
    app: mktxp-exporter
spec:
  selector:
    app: mktxp-exporter
  ports:
    - name: http
      port: 49090
      targetPort: 49090
