apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: alloy
  labels:
    release: observability
spec:
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
