apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: private
  tls:
    - hosts:
        - argo.kube.kalski.xyz
      secretName: argocd-server-tls
  rules:
    - host: argo.kube.kalski.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
